### ISSUE TITLE
Get wrong context.js using npm install

### ISSUE THREAD

**Issue by littledumb** [zedgu/surface#4]
I got an error message saying "getFields is not defined". I found that context.js has some strange codes:

```
module.exports = function(app, surface) {
  var context = app.context;

  context.format = format;
  context.inputs = inputs;
  Object.defineProperty(context, 'fields', {get: getFields, set: setFields});
};
```

I installed surface using `npm install surface --save`.

**Comment by zedgu** [comment]
So sorry for that.
Please check the v0.7.10 .
