### ISSUE TITLE
Changing root path results in regex error

### ISSUE THREAD

**Issue by DanPantry** [zedgu/surface#5]
Hi, I'm just trying to change the root path from `'./lib'` to `'./server'` as per your example. Here is my code.

````javascript
'use strict';
const koa = require('koa');
const surface = require('surface');
const path = require('path');

const app = koa();
surface(app, {
  root: './server'
});

app.listen(3000);
````

And the resulting error:
````
c:\loluk\node_modules\surface\node_modules\koa-ovenware\node_modules\ovenware\lib\loader.js:38
        paths[file.replace(new RegExp('^' + path.join(path.resolve(root), '/')
                           ^
SyntaxError: Invalid regular expression: /^c:\loluk\server\controllers\/: \ at end of pattern
````

Using `surface` version `0.7.11`, `koa` version `0.21.0`, iojs version `v2.2.1` and windows 7 x64.

It would appear this is an error at ovenware, but it may be worth having here

**Comment by DanPantry** [comment]
It appears this error presents itself even without changing the path, due to the way Windows formats it's drives (`c:\loluk` instead of `/c/loluk`)

**Comment by zedgu** [comment]
try the new version of v0.7.12
